export const formatAluno = {
  nome: "Nome do Aluno",
  cpf: "CPF do Aluno",
  rg: "RG do Aluno",
  email: "Email do Aluno",
  sexo: "Sexo do Aluno",
  serie: "Série",
  turma: "Turma",
  anoTurma: "Ano Turma",
  nomeResponsavel: "Nome do Responsável",
  cpfResponsavel: "CPF do Responsável",
  telefoneResponsavel: "Telefone do Responsável",
  emailResponsavel: "Email do Responsável",
  cep: "CEP",
  bairro: "Bairro",
  endereco: "Endereço",
  complemento: "Complemento",
  estadoMatricula: "Estado da Matrícula",
};

export const mockAluno = {
  nome: "Joãozinho da Silva",
  cpf: 12345678910,
  rg: 123456789,
  email: "joaozinho@email.com",
  nomeResponsavel: "João da Silva",
  cpfResponsavel: 98765432101,
  telefoneResponsavel: 44912345678,
  emailResponsavel: "joao@email.com",
  cep: 123456789,
  bairro: "Jardim Felicidade",
  endereco: "Rua Primeiro de Janeiro",
  complemento: "Não",
  estadoMatricula: "Matriculado",
};

export const mockAlunoList = [
  {
    nome: "Joãozinho da Silva",
    cpf: "123.456.789-10",
    rg: "12.345.678-9",
    email: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "c",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
    estadoMatricula: "Matriculado",
  },
  {
    nome: "Paulinho da Silva",
    cpf: "123.456.789-11",
    rg: "12.345.678-9",
    email: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
    estadoMatricula: "Matriculado",
  },
  {
    nome: "Carlinhos da Silva",
    cpf: "123.456.789-12",
    rg: "12.345.678-9",
    email: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
    estadoMatricula: "Matriculado",
  },
  {
    nome: "Maria da Silva",
    cpf: "078.005.679-58",
    rg: "12.345.678-9",
    email: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
    estadoMatricula: "Matriculado",
  },
  {
    nome: "TESTE",
    cpf: "078.005.679-58",
    rg: "12.345.678-9",
    email: "TESTE@email.com",
    sexoAluno: 1,
    serie_turma: "2",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
    estadoMatricula: "Matriculado",
  },
];
