export const formatAluno = {
  nomeAluno: 'Nome do Aluno',
  cpfAluno: "CPF do Aluno",
  rgAluno: "RG do Aluno",
  emailAluno: "Email do Aluno",
  sexoAluno: "Sexo do Aluno",
  serie_turma: "Série",
  turma: "Turma",
  nomeResponsavel: "Nome do Responsável",
  cpfResponsavel: "CPF do Responsável",
  telefoneResponsavel: "Telefone do Responsável",
  emailResponsavel: "Email do Responsável",
  cep: "CEP",
  bairro: "Bairro",
  endereco: "Endereço",
  complemento: "Complemento",
}

export const mockAluno = {
  nomeAluno: 'Joãozinho da Silva',
  cpfAluno: "123.456.789-10",
  rgAluno: "12.345.678-9",
  emailAluno: "joaozinho@email.com",
  nomeResponsavel: "João da Silva",
  cpfResponsavel: "987.654.321-01",
  telefoneResponsavel: "(44) 9 1234-5678",
  emailResponsavel: "joao@email.com",
  cep: "123456789",
  bairro: "Jardim Felicidade",
  endereco: "Rua Primeiro de Janeiro",
  complemento: "Não",
};

export const mockAlunoList = [
  {
    nomeAluno: 'Joãozinho da Silva',
    cpfAluno: "123.456.789-10",
    rgAluno: "12.345.678-9",
    emailAluno: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
  },
  {
    nomeAluno: 'Paulinho da Silva',
    cpfAluno: "123.456.789-10",
    rgAluno: "12.345.678-9",
    emailAluno: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
  },
  {
    nomeAluno: 'Carlinhos da Silva',
    cpfAluno: "123.456.789-10",
    rgAluno: "12.345.678-9",
    emailAluno: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
  },
  {
    nomeAluno: 'Maria da Silva',
    cpfAluno: "123.456.789-10",
    rgAluno: "12.345.678-9",
    emailAluno: "joaozinho@email.com",
    sexoAluno: 1,
    serie_turma: "1",
    turma: "a",
    nomeResponsavel: "João da Silva",
    cpfResponsavel: "987.654.321-01",
    telefoneResponsavel: "(44) 9 1234-5678",
    emailResponsavel: "joao@email.com",
    cep: "123456789",
    bairro: "Jardim Felicidade",
    endereco: "Rua Primeiro de Janeiro",
    complemento: "Não",
  },
];
