export const formatProfessor = {
    nome: 'Nome',
    cpf: "CPF",
    rg: "RG",
    email: "Email",
    telefone: "Telefone",
    formacao: "Formação",
    disciplinas: "Disciplinas",
    cep: "CEP",
    bairro: "Bairro",
    endereco: "Endereço",
    complemento: "Complemento",
}

export const mockProfessor = {
    nome: 'Lucas Aurélio',
    cpf: "123.456.789-11",
    rg: "12.345.678-9",
    email: "lucas@email.com",
    telefone: "(44) 9 9876-5432",
    disciplinas: ["Matemática","Física"],
    cep: "12.345.678",
    bairro: "Jardim trinta e um de dezembro",
    endereco: "Rua nove de maio",
    complemento: "Apartamento 6",
};

export const mockProfessorList = [
    {
        nome: 'Lucas Aurélio',
        cpf: "123.456.789-11",
        rg: "12.345.678-9",
        email: "lucas@email.com",
        telefone: "(44) 9 9876-5432",
        formacao: "Doutorado",
        disciplinas: ["Matemática,","   Física"],
        cep: "12.345.678",
        bairro: "Jardim trinta e um de dezembro",
        endereco: "Rua nove de maio",
        complemento: "Apartamento 6",
    },
    {
        nome: 'Marco Pinheiro',
        cpf: "123.456.789-11",
        rg: "12.345.678-9",
        email: "marco@email.com",
        telefone: "(44) 9 9876-5432",
        formacao: "Doutorado",
        disciplinas: ["Geografia,","   Ciências"],
        cep: "12.345.678",
        bairro: "Conjunto doze de junho",
        endereco: "Rua cinco de dezembro",
        complemento: "Casa A",
    },
    {
        nome: 'Matheus Henrique',
        cpf: "123.456.789-11",
        rg: "12.345.678-9",
        email: "matheus@email.com",
        telefone: "(44) 9 9876-5432",
        formacao: "Doutorado",
        disciplinas: ["Matemática"],
        cep: "12.345.678",
        bairro: "Jardim vinte e três de março",
        endereco: "Rua trinta de dezembro",
        complemento: "Perto do Banco",
    },
    {
        nome: 'Ana Ribeiro',
        cpf: "123.456.789-11",
        rg: "12.345.678-9",
        email: "ana@email.com",
        telefone: "(44) 9 9876-5432",
        formacao: "Mestrado",
        disciplinas: ["História"],
        cep: "12.345.678",
        bairro: "Conjunto quinze abril",
        endereco: "Rua dezessete de outubro",
        complemento: "Apartamento 7",
    },
    {
        nome: 'Cláudia Leite Henrique',
        cpf: "123.456.789-11",
        rg: "12.345.678-9",
        email: "claudia@email.com",
        telefone: "(44) 9 9876-5432",
        formacao: "Doutorado",
        disciplinas: ["Ciências"],
        cep: "12.345.678",
        bairro: "Jardim oito de julho",
        endereco: "Rua dezoito de junho",
        complemento: "Casa B",
    },
];